/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JOptionPane;


/**
 *
 * @author Prahallad
 */
public class rprofile extends javax.swing.JFrame {

    /**
     * Creates new form rprofile
     */
    public rprofile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        res = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        ci = new javax.swing.JTextField();
        ct = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pass = new javax.swing.JTextField();
        em = new javax.swing.JTextField();
        user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RESTAURENT DETAILS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 788, 28));

        res.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(res, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 236, 268, -1));

        add.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 276, 268, -1));

        ci.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(ci, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 316, 268, -1));

        ct.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(ct, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 356, 268, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setText("SUBMIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 412, -1, -1));

        pass.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 196, 268, -1));

        em.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(em, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 156, 268, -1));

        user.setBackground(new java.awt.Color(255, 255, 204));
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 116, 268, -1));

        jLabel2.setText("USERNAME");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 119, 168, -1));

        jLabel3.setText("EMAIL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 159, 168, -1));

        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 199, 168, -1));

        jLabel5.setText("RESTAURENT NAME");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 239, 168, -1));

        jLabel6.setText("ADDRESS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 279, 168, -1));

        jLabel7.setText("CITY");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 319, 168, -1));

        jLabel8.setText("CONTACT");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 359, 168, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setText("LOGIN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 467, -1, -1));

        jLabel9.setText("go to Login -");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 470, 81, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        rlogin rl = new rlogin();
        rl.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String username = user.getText();
String password = pass.getText();
String email = em.getText();
String name = res.getText();
String address = add.getText();
String city = ci.getText();
String contact = ct.getText();

String emailPattern = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
// Check if any field is empty
if (username.isEmpty() || password.isEmpty() || email.isEmpty() || name.isEmpty() ||
    address.isEmpty() || city.isEmpty() || contact.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Please fill in all fields.");
} 
// Check if contact is exactly 10 digits
else if (!contact.matches("\\d{10}")) {
    JOptionPane.showMessageDialog(this, "Contact number must be exactly 10 digits.");
} 
// Check if email format is valid
else if (!email.matches(emailPattern)) {
    JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
}
else {
    try {
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/HUNGER", "root", "Root");
        Statement st = conn.createStatement();
        
        // Check if email, username, or contact already exists
        String checkQuery = "SELECT * FROM HUNGER.RESTAURENT WHERE email = '" + email + "' OR username = '" + username + "' OR contact = '" + contact + "'";
        ResultSet rs = st.executeQuery(checkQuery);
        
        if (rs.next()) {
            // If any record is found, display an error message
            if (rs.getString("email").equals(email)) {
                JOptionPane.showMessageDialog(this, "Email already exists. Please use a different email.");
            } else if (rs.getString("username").equals(username)) {
                JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different username.");
            } else if (rs.getString("contact").equals(contact)) {
                JOptionPane.showMessageDialog(this, "Contact number already exists. Please use a different contact number.");
            }
        } else {
            // No duplicates found, proceed with insertion
            String query1 = "INSERT INTO HUNGER.RESTAURENT"
                    + " (username, email, password, name, address, city, contact)"
                    + " VALUES('" + username + "','" + email + "','" + password + "','" + name + "','" + address + "','" + city + "','" + contact + "')";
            st.executeUpdate(query1);

            JOptionPane.showMessageDialog(this, "Registration was Successful, Please Login");

            // Clear fields after successful registration
            user.setText("");
            pass.setText("");
            em.setText("");
            res.setText("");
            add.setText("");
            ci.setText("");
            ct.setText("");
        }
        
        // Close resources
        rs.close();
        st.close();
        conn.close();
        
    } catch (Exception e) {
        System.out.println(e.getMessage());
    }
}

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rprofile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rprofile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.JTextField ci;
    private javax.swing.JTextField ct;
    private javax.swing.JTextField em;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField res;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
